daiyndal_showcase/urls.py
from django.contrib import admin
from django.urls import include, path
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    path("admin/", admin.site.urls),
    path("", include("myapp.urls")),
]

if settings.DEBUG:
    urlpatterns.extend(static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT))

myapp/urls.py
from django.contrib.staticfiles.storage import staticfiles_storage
from django.urls import path
from django.contrib.auth import views as auth_views
from django.views.generic.base import RedirectView
from django.contrib.auth.decorators import login_required
from . import views, forms

urlpatterns = [
    # Setup nginx to serve favicon https://simpleit.rocks/python/django/django-favicon-adding/
    path(
        "favicon.ico",
        RedirectView.as_view(url=staticfiles_storage.url("favicon.ico")),
    ),
    path("", views.index, name="index"),
    path("about/", views.about, name="about"),
    path("courses/", views.CourseList.as_view(), name="courses"),
    path("courses/<int:pk>/", views.CourseDetailView.as_view(), name="course-detail"),
    path(
        "my-courses/",
        login_required(views.MyCourseList.as_view(), login_url="/login"),
        name="my-courses",
    ),
    path("unit/<int:unit_id>/step/<int:step_id>/", views.lesson, name="lesson"),
    path("course-ended/<int:course_id>/", views.course_ended, name="course-ended"),
    path("tests/<int:test_id>/", views.get_test),
    path("save-test/", views.save_test),
    path(
        "delete-attendance/<int:course_id>/",
        views.delete_attendance,
        name="delete-attendance",
    ),
    path("get-passed-percentage/", views.get_passed_percentage),
    path("login/", views.login_user, name="login"),
    path("register/", views.register_user, name="register"),
    path(
        "registration-continued/",
        views.registration_continued,
        name="register_continue",
    ),
    path("logout/", views.logout_user, name="logout"),
    path("password_reset/", views.password_reset_request, name="password_reset"),
    path(
        "password_reset/done/",
        auth_views.PasswordResetDoneView.as_view(
            template_name="myapp/password_reset_done.html"
        ),
        name="password_reset_done",
    ),
    path(
        "reset/<uidb64>/<token>/",
        auth_views.PasswordResetConfirmView.as_view(
            template_name="myapp/password_reset_confirm.html",
            form_class=forms.MySetPasswordForm,
        ),
        name="password_reset_confirm",
    ),
    path(
        "reset/done/",
        auth_views.PasswordResetCompleteView.as_view(
            template_name="myapp/password_reset_complete.html"
        ),
        name="password_reset_complete",
    ),
    path("profile/", views.profile, name="profile"),
]

myapp/models.py
from django.db import models
from django.contrib.auth.models import AbstractBaseUser, BaseUserManager


class UserManager(BaseUserManager):
    def create_user(self, email, user_firstname, user_lastname, password=None):
        if not email:
            raise ValueError("Users must have an email address")
        if not user_firstname or not user_lastname:
            raise ValueError("Users must have firstname and lastname")

        user = self.model(
            email=self.normalize_email(email),
            user_firstname=user_firstname,
            user_lastname=user_lastname,
        )
        user.set_password(password)
        user.save(using=self._db)
        return user

    def create_superuser(self, email, user_firstname, user_lastname, password=None):
        user = self.create_user(
            email=self.normalize_email(email),
            user_firstname=user_firstname,
            user_lastname=user_lastname,
            password=password,
        )
        user.is_admin = True
        user.is_staff = True
        user.is_superuser = True
        user.save(using=self._db)
        return user


class User(AbstractBaseUser):
    username = None
    email = models.EmailField("email address", unique=True)
    is_admin = models.BooleanField(default=False)
    is_active = models.BooleanField(default=True)
    is_staff = models.BooleanField(default=False)
    is_superuser = models.BooleanField(default=False)

    user_firstname = models.CharField(max_length=50)
    user_lastname = models.CharField(max_length=50)
    user_phone_number = models.CharField(max_length=13, null=True)
    user_lang = models.CharField(
        max_length=2,
        choices=[
            ("ru", "Рус"),
            ("kz", "Қаз"),
        ],
        default="ru",
    )
    user_school_name = models.CharField(max_length=100, null=True)
    user_grade = models.IntegerField(null=True)
    user_location = models.CharField(max_length=50, null=True)

    USERNAME_FIELD = "email"
    REQUIRED_FIELDS = ["user_firstname", "user_lastname"]
    objects = UserManager()

    def __str__(self):
        return self.user_firstname + " " + self.user_lastname

    def has_perm(self, perm, obj=None):
        return self.is_admin

    def has_module_perms(self, app_label):
        return True


class Supervisor(models.Model):
    # TODO: proper supervisor model
    pass


class Course(models.Model):
    course_id = models.AutoField(primary_key=True)
    course_name = models.CharField(max_length=30)
    course_description = models.CharField(max_length=300)
    course_avatar = models.CharField(
        max_length=300, default="/static/img/course_avatar/math-avatar.png"
    )
    course_thumbnail = models.CharField(
        max_length=300, default="/static/img/course_thumbnail/math-card.jpg"
    )
    course_supervisor = models.CharField(max_length=100)
    course_supervisor_avatar = models.CharField(
        max_length=300,
        default="https://cdn0.iconfinder.com/data/icons/user-pictures/100/male-512.png",
    )
    active = models.BooleanField(default=False)
    # course_supervisor=models.ForeignKey(Supervisor, on_delete=models.CASCADE)
    def __str__(self):
        return self.course_name


class Theme(models.Model):
    theme_id = models.AutoField(primary_key=True)
    theme_name = models.CharField(max_length=30)
    theme_order = models.IntegerField(default=0)
    course = models.ForeignKey(Course, on_delete=models.CASCADE)

    def save(self, force_insert=False, force_update=False):
        # Only modify number if creating for the first time (is default 0)
        if self.theme_order == 0:
            # Grab the highest current index (if it exists)
            try:
                last = Theme.objects.filter(course__exact=self.course).order_by(
                    "theme_order"
                )[0]
                self.theme_order = last.theme_order + 1
            except IndexError:
                self.theme_order = 1
        # Call the "real" save() method
        super(Theme, self).save(force_insert, force_update)

    def __str__(self):
        return str(self.course) + ">" + self.theme_name


class Unit(models.Model):
    unit_id = models.AutoField(primary_key=True)
    unit_name = models.CharField(max_length=100)
    unit_description = models.CharField(max_length=100)
    theme = models.ForeignKey(Theme, on_delete=models.CASCADE)
    unit_order = models.IntegerField(default=0)
    author_name = models.CharField(max_length=100, null=True)

    class Meta:
        unique_together = ("theme", "unit_order")

    def save(self, force_insert=False, force_update=False):
        # Only modify number if creating for the first time (is default 0)
        if self.unit_order == 0:
            # Grab the highest current index (if it exists)
            try:
                last = Unit.objects.filter(theme__exact=self.theme).order_by(
                    "unit_order"
                )[0]
                self.unit_order = last.unit_order + 1
            except IndexError:
                self.unit_order = 1
        # Call the "real" save() method
        super(Unit, self).save(force_insert, force_update)

    def __str__(self):
        return str(self.theme) + ">" + self.unit_name


class Step(models.Model):
    step_id = models.AutoField(primary_key=True)
    step_name = models.CharField(max_length=100, blank=True)
    step_order = models.PositiveSmallIntegerField(default=0)
    # step_type: 0 - HTML, 1 - Test
    step_type = models.PositiveSmallIntegerField(
        choices=(
            (0, "HTML"),
            (1, "Test"),
        ),
        default=0,
    )
    unit = models.ForeignKey(Unit, on_delete=models.CASCADE)

    class Meta:
        unique_together = ("unit", "step_order")

    def save(self, force_insert=False, force_update=False):
        # Only modify number if creating for the first time (is default 0)
        if self.step_order == 0:
            # Grab the highest current index (if it exists)
            try:
                last = Step.objects.filter(unit=self.unit).order_by("-step_order")[0]
                print(last.step_order)
                self.step_order = last.step_order + 1
            except IndexError:
                print("Index Error Happened")
                self.step_order = 1
        # Call the "real" save() method
        super(Step, self).save(force_insert, force_update)

    def __str__(self):
        return (
            str(self.unit)
            + ">"
            + str(self.step_order)
            + (" HTML", " Test")[self.step_type]
        )


class Test(models.Model):
    test_id = models.AutoField(primary_key=True)
    test_json = models.TextField(blank=True, default="")
    # test_difficulty: 1-3 difficulty
    test_difficulty = models.PositiveSmallIntegerField(
        choices=(
            (1, "Easy"),
            (2, "Medium"),
            (3, "Hard"),
        ),
        default=1,
    )
    step = models.ForeignKey(Step, on_delete=models.CASCADE)

    def __str__(self):
        return str(self.step)


class QuestionGroup(models.Model):
    test = models.ForeignKey(Test, on_delete=models.CASCADE)
    qg_text = models.TextField(null=True, blank=True)


class Question(models.Model):
    question_group = models.ForeignKey(QuestionGroup, on_delete=models.CASCADE)
    question_text = models.CharField(max_length=200)
    # a1 is correct answer by default
    a1 = models.CharField(max_length=100, help_text="This must be correct answer")
    a2 = models.CharField(max_length=100)
    a3 = models.CharField(max_length=100)
    a4 = models.CharField(max_length=100)


class CompletedQuestion(models.Model):
    user = models.ForeignKey(User, on_delete=models.CASCADE)
    question = models.ForeignKey(Question, on_delete=models.CASCADE)
    cq_correct = models.BooleanField()


class HTML(models.Model):
    content = models.TextField()
    step = models.OneToOneField(Step, on_delete=models.CASCADE, primary_key=True)

    def __str__(self):
        return str(self.step)


class CourseAttd(models.Model):
    user = models.ForeignKey(User, on_delete=models.CASCADE)
    course = models.ForeignKey(Course, on_delete=models.DO_NOTHING)
    finished_steps = models.TextField(blank=True)
    stop_on = models.IntegerField(default=0)
    active = models.BooleanField(default=True)

myapp/templates/myapp/about.html
{% extends "base.html" %}
{% block title %}Войти в систему{% endblock title %}
{% block content %}
{% load static %}
<body style="background-color: #F5F5F5">
    {% if user.is_authenticated %}
    <nav class="navbar navbar-light navbar-expand-md pb-2 pb-md-4 bg-white border-bottom">
        <div class="container-fluid"><a class="navbar-brand d-inline-block d-md-none" href="/"><img src="{% static '/img/daiyndal-icon.png' %}" width="162" height="36"></a><button data-bs-toggle="collapse" class="navbar-toggler" data-bs-target="#navcol-2"><span class="visually-hidden">Toggle navigation</span><span class="navbar-toggler-icon"></span></button>
            <div class="collapse navbar-collapse mx-auto pt-md-4 px-2 position-relative justify-content-between" id="navcol-2">
                <ul class="navbar-nav">
                    <li class="nav-item"><a class="nav-link active" href="/courses/">Каталог</a></li>
                    <li class="nav-item"><a class="nav-link" href="/my-courses/">Мои курсы</a></li>
                    <li class="nav-item d-block d-md-none"><a class="nav-link" href="/profile/">Профиль</a></li>
                    <li class="nav-item"><a class="nav-link d-block d-md-none" href="/logout/">Выйти</a></li>
                </ul>
                <a class="translate-middle-x start-50 position-absolute" href="/"><img class="d-none d-md-inline-block" src="{% static '/img/daiyndal-icon.png' %}" width="162" height="36"></a>
                <div class="nav-item dropdown d-none d-md-block"><a id="profile" class="mx-lg-3 nav-link" role="button" data-bs-toggle="dropdown" aria-expanded="false" style="padding-left: 0; padding-right: 0;">{{request.user.user_firstname}}<i class="fas fa-user" style="font-size: 25px; margin-left: 10px"></i></a>
                    <ul class="dropdown-menu" aria-labelledby="profile">
                        <li class="dropdown-item disabled">{{ request.user }}</li>
                        <li class="dropdown-item"><hr class="dropdown-divider" /></li>
                        <li class="dropdown-item"><a href="/profile/">Профиль</a></li>
                        <li class="dropdown-item"><a href="/my-courses/">Мои курсы</a></li>
                        <li class="dropdown-item"><a href="/logout/">Выйти</a></li>
                    </ul>
                </div>
            </div>
        </div>
    </nav>
    {% else %}
    <nav class="navbar navbar-light navbar-expand-md">
        <div class="container-fluid">
            <a class="navbar-brand d-inline-block d-md-none" href="#">
                <img src="{% static '/img/daiyndal-icon.png' %}" width="162" height="36">
            </a>
            <button data-bs-toggle="collapse" class="navbar-toggler" data-bs-target="#navcol-2">
                <span class="visually-hidden">Toggle navigation</span>
                <span class="navbar-toggler-icon"></span>
            </button>
            <div class="collapse navbar-collapse mx-auto pt-md-4 px-2 position-relative justify-content-between" id="navcol-2" style="max-width: 1400px;">
                <a class="btn btn-dark" href="/courses/">Курсы</a>
                <a class="d-none d-md-inline-block translate-middle-x start-50 position-absolute" href="/"><img src="{% static '/img/daiyndal-icon.png' %}" width="162" height="36"></a>
                <form>
                    <a class="btn btn-primary mx-1 mx-lg-3" href="/login/">Войти</a>
                    <a class="btn btn-outline-primary" href="/register/">Регистрация</a>
                </form>
            </div>
        </div>
    </nav>
    {% endif %}    
    <section class="pt-1 pb-4 py-md-5">
        <div class="container">
            <h2 class="big-heading">Наши цели</h2>
            <p>daiyndal в первую очередь нацелен для того чтобы сделать подготовку к НИШ более доступной. Начниная с маленького колличества курсов для подготовки к НИШ мы будем развивать daiyndal. Нашей финальной целью является сделать платформу которая полностью заменит внешкольное обучение для большинства школьников Казахстана.</p>
        </div>
    </section>
    <section id="courses" class="pt-1 pb-4 py-md-5">
        <div class="container">
            <h2 class="big-heading">Сотрудничество</h2>
            <p>Мы открыты к предложениям сотрудничества с нашей командой и платформой. Просим обращатся на почту: <a class="primary-link" href="mailto:daiyndalgroup@gmail.com">daiyndalkz@gmail.com</a></p>
        </div>
    </section>
    {% include "myapp/partials/base-footer.html" %}
    <script src="{% static '/bootstrap/js/bootstrap.min.js' %}"></script>
</body>
{% endblock content %}

myapp/templates/myapp/password_reset.html
{% extends "base.html" %}
{% block title %}Сброс пароля{% endblock title %}
{% block content %}
{% load static %}
<body style="background-color: #F5F5F5;">
    <div class="container-fluid mx-auto">
        <section style="margin: 8em 0em;">
            <div class="row d-flex">
                <div class="col text-center"><img src="{% static 'img/daiyndal-icon.png' %}" width="254" height="56"></div>
            </div>
            <div class="row">
                <div class="col">
                    <h4 class="text-center my-4" style="font-family: Raleway;">Сброс пароля</h4>
                </div>
            </div>
            <div class="row d-flex justify-content-xl-center">
                <div class="col offset-xl-0 text-center">
                    <div class="mx-auto px-3 px-md-5 py-4"
                        style="background: var(--bs-white);max-width: 570px;border-radius: 1.2rem;">
                        <p class="form-text text-start" style="width: 100%;font-size: 16px;">Мы отправим вам письмо для сброса пароля</p>
                        <form method="POST">
                            {% csrf_token %}
                            <div class="mb-3">
                                <label class="form-label text-start" for="{{ password_reset_form.email.id_for_label }}" style="width: 100%;font-size: 18px;">Почта</label>
                                {{ password_reset_form.email }}
                            </div>
                            <button class="btn btn-primary d-block" type="submit"
                            style="width: 100%;border-radius: 0.7rem;height: 50px;">Отправить письмо</button>
                        </form>
                    </div>
                </div>
            </div>
        </section>
    </div>
</body>
{% endblock content %}

myapp/templates/myapp/profile.html
{% extends 'base.html' %}
{% block title %}Профиль{% endblock title %}
{% block content %}
{% load static %}
<body style="background-color: #F5F5F5">
    <nav class="navbar navbar-light navbar-expand-md pb-2 pb-md-4 bg-white border-bottom">
        <div class="container-fluid"><a class="navbar-brand d-inline-block d-md-none" href="/"><img src="{% static '/img/daiyndal-icon.png' %}" width="162" height="36"></a><button data-bs-toggle="collapse" class="navbar-toggler" data-bs-target="#navcol-2"><span class="visually-hidden">Toggle navigation</span><span class="navbar-toggler-icon"></span></button>
            <div class="collapse navbar-collapse mx-auto pt-md-4 px-2 position-relative justify-content-between" id="navcol-2">
                <ul class="navbar-nav">
                    <li class="nav-item"><a class="nav-link" href="/courses/">Каталог</a></li>
                    <li class="nav-item"><a class="nav-link" href="/my-courses/">Мои курсы</a></li>
                    <li class="nav-item d-block d-md-none"><a class="nav-link active" href="/profile/">Профиль</a></li>
                    <li class="nav-item"><a class="nav-link d-block d-md-none" href="/logout/">Выйти</a></li>
                </ul>
                <a class="translate-middle-x start-50 position-absolute" href="/"><img class="d-none d-md-inline-block" src="{% static '/img/daiyndal-icon.png' %}" width="162" height="36"></a>
                <div class="nav-item dropdown d-none d-md-block"><a id="profile" class="mx-lg-3 nav-link" role="button" data-bs-toggle="dropdown" aria-expanded="false" style="padding-left: 0; padding-right: 0;">{{request.user.user_firstname}}<i class="fas fa-user" style="font-size: 25px; margin-left: 10px"></i></a>
                    <ul class="dropdown-menu" aria-labelledby="profile">
                        <li class="dropdown-item disabled">{{ request.user }}</li>
                        <li class="dropdown-item disabled"><hr class="dropdown-divider" /></li>
                        <li class="dropdown-item"><a href="/profile/">Профиль</a></li>
                        <li class="dropdown-item"><a href="/my-courses/">Мои курсы</a></li>
                        <li class="dropdown-item"><a href="/logout/">Выйти</a></li>
                    </ul>
                </div>
            </div>
        </div>
    </nav> 
    <div class="container mt-5">
        <div class="row">
            <div class="col-md-3 d-none d-lg-block">
                <div class="card p-3 panel">
                    <ul class="list-group list-group-flush">
                        <li class="list-group-item active"><a href="/profile/"><i class="far fa-user-circle"></i>Профиль</a></li>
                        <li class="list-group-item"><a href="/my-courses/"><i class="fas fa-th-list"></i>Мои курсы</a></li>
                    </ul>
                </div>
            </div>
            <div class="col-lg-9">
                <form method="POST">
                    {% csrf_token %}
                    <div class="row mb-3">
                        <div class="col-12 col-md-6 flex-column">
                            <div class="col mb-3">
                                <label class="form-label text-start" for="{{form.email.id_for_label}}" style="width: 100%;font-size: 18px;">Почта</label>
                                {{form.email}}
                            </div>
                            <div class="col mb-3">
                                <label class="form-label text-start" for="{{form.user_firstname.id_for_label" style="width: 100%;font-size: 18px;">Имя</label>
                                {{form.user_firstname}}
                            </div>
                            <div class="col mb-3">
                                <label class="form-label text-start" for="{{form.user_lastname.id_for_label}}" style="width: 100%;font-size: 18px;">Фамилия</label>
                                {{form.user_lastname}}
                            </div>
                            <div class="col mb-3">
                                <label class="form-label text-start" for="{{form.user_phone_number.id_for_label}}" style="width: 100%;font-size: 18px;">Номер Телефона</label>
                                {{form.user_phone_number}}
                            </div>
                        </div>
                        <div class="col-12 col-md-6 flex-column">
                            <div class="col mb-3">
                                <label class="form-label text-start" for="{{form.user_lang.id_for_label}}" style="width: 100%;font-size: 18px;">Язык обучения</label>
                                <select id="id_user_lang" name="user_lang" class="form-select">
                                    
                                    <option value="ru" {% if form.user_lang.value == "ru" %}selected=""{%endif%}>Рус</option>
                                    <option value="kz" {% if form.user_lang.value == "kz" %}selected=""{%endif%}>Қаз</option>
                                </select></div>
                            <div class="col mb-3"><label class="form-label text-start" for="{{form.user_grade.id_for_label}}" style="width: 100%;font-size: 18px;">Год обучения</label>
                                <select  id="id_user_grade" name="user_grade" class="form-select">
                                    <option value="5" {% if form.user_grade.value == 5 %}selected=""{%endif%}>5</option>
                                    <option value="6" {% if form.user_grade.value == 6 %}selected=""{%endif%}>6</option>
                                </select></div>
                            <div class="col mb-3">
                                <label class="form-label text-start" for="{{form.user_school_name.id_for_label}}" style="width: 100%;font-size: 18px;">Школа</label>
                                {{form.user_school_name}}
                            </div>
                            <div class="mb-3">
                                <label class="form-label text-start" for="{{form.user_location.id_for_label}}" style="width: 100%;font-size: 18px;">Город или населенный пункт</label>
                                {{form.user_location}}
                            </div>
                        </div>
                    </div>
                    <button class="btn btn-primary d-block w-25" type="submit" style="width: 100%;border-radius: 0.7rem;height: 50px;">Сохранить</button>
                </form>
            </div>
        </div>
    </div>
    <script src="{% static '/bootstrap/js/bootstrap.min.js' %}"></script>
</body>
{% endblock %}

myapp/templates/myapp/registration-continued.html
{% extends "base.html" %}
{% block title %}Регистрация{% endblock %}
{% block content %}
{% load static %}
<body style="background-color: #F5F5F5;">
    <div class="container-fluid">
        <section style="margin: 3em 0em;">
            <div class="row d-flex">
                <div class="col text-center"><img src="{% static 'img/daiyndal-icon.png' %}" width="162" height="36"></div>
            </div>
            <div class="row">
                <div class="col">
                    <h2 class="text-center mt-4" style="font-family: Raleway, sans-serif;font-weight: bold;height: 36px;font-size: 36px;">Регистрация</h2>
                    <p class="text-center text-secondary my-3" style="font-family: Raleway;">Ответьте на вопросы чтобы закончить регистрацию</p>
                </div>
            </div>
            <div id="app" class="mx-auto px-2 px-md-5 py-4 mt-4" style="background: var(--bs-white);max-width: 570px;border-radius: 1.2rem;">
                <form @submit="formValidate" method="POST" novalidate>
                    {% csrf_token %}
                    <div class="mb-3">
                        <label class="form-label text-start" for="{{form.user_grade.id_for_label}}" style="width: 100%;font-size: 18px;">Год обучения</label>
                        <select id="id_user_grade" name="user_grade" class="form-select" v-model="grade" :class="{ 'is-invalid': errors.lang }">
                            <option value="" selected="">Выберите ваш класс</option>
                            <option value="5">5</option>
                            <option value="6">6</option>
                        </select>
                    </div>
                    <div class="mb-3">
                        <label class="form-label text-start" for="{{form.user_lang.id_for_label}}" style="width: 100%;font-size: 18px;">Язык обучения</label>
                        <select id="id_user_lang" name="user_lang" class="form-select" v-model="lang" :class="{ 'is-invalid': errors.lang }">
                            <option value="" selected>Выберите язык обучения</option>
                            <option value="ru">Рус</option>
                            <option value="kz">Қаз</option>
                        </select></div>
                    <div class="mb-3">
                        <label class="form-label text-start" for="{{ form.user_phone_number.id_for_label }}" style="width: 100%;font-size: 18px;">Номер телефона</label>
                        {{ form.user_phone_number }}
                        <small class="form-text text-danger">[[ phoneHelp ]]</small>
                    </div>
                    <div class="mb-3">
                        <label class="form-label text-start" for="{{ form.user_school_name.id_for_label }}" style="width: 100%;font-size: 18px;">Школа</label>
                        {{ form.user_school_name }}
                        <small class="form-text text-danger">[[ schoolHelp ]]</small>
                    </div>
                    <div class="mb-3">
                        <label class="form-label text-start" for="{{ form.user_school_name.id_for_label }}" style="width: 100%;font-size: 18px;">Город или населенный пункт</label>
                        {{ form.user_location }}
                        <small class="form-text text-danger">[[ locationHelp ]]</small>
                    </div>
                    <button class="btn btn-primary d-block" type="submit" style="width: 100%;border-radius: 0.7rem;height: 50px;">Далее</button>
                </form>
            </div>
        </section>
    </div>
    <script src="{% static '/bootstrap/js/bootstrap.min.js' %}"></script>
    <script src="https://unpkg.com/vue@next"></script>
    <script>
    const App = {
        data(){
            return {
                "phone": "",
                "school": "",
                "grade": "",
                "lang": "",
                "location": "",
                errors: {
                    "phone": false,
                    "school": false,
                    "grade": false,
                    "lang": false,
                    "location": false,
                }
            }
        },
        computed: {
            phoneHelp(){
                if (this.phone==""){
                    return "";
                }
                if(!this.phoneValidate()){
                    this.errors.phone = true;
                    return "Введите верный номер мобильного телефона в формате 87771234133 или +77771234133";
                }else{
                    this.errors.phone = false;
                    return "";
                } 
            },
            schoolHelp(){
                if(!this.schoolValidate()){
                    return "Введите название школы в которой вы обучаетесь.";
                } else {
                    return "";
                }
            },
            locationHelp(){
                if(!((!this.errors.location && this.location=="") || this.locationValidate())){
                    return "Введите название города или населенного пункта в котором вы проживаете.";
                } else {
                    return "";
                }
            }
        },
        methods: {
            phoneValidate() {
                const re = /^(\s*)?(\+)?([- _():=+]?\d[- _():=+]?){11,11}(\s*)?$/;
                return re.test(this.phone);
            },
            schoolValidate(){
                if(this.school!=""){
                    this.errors.school = false;
                    return true;
                }
                this.errors.school = true;
                return false;
            },
            locationValidate(){
                if(!(/^(\d*)$/.test(this.location))){
                    this.errors.location = false;
                    return true;
                }
                this.errors.location = true;
                return false;
            },
            formValidate: function (e) {
                let has_error = false;
                if (!this.phoneValidate || this.phone=="") {
                    this.errors.phone = true;
                    has_error = true;
                }
                if (this.school=="") {
                    this.errors.school = true;
                    has_error = true;
                }
                if (this.location=="" || !this.locationValidate()){
                    this.errors.location = true;
                    has_error = true;    
                }
                if (this.lang==""){
                    this.errors.lang = true;
                    has_error = true;    
                }
                if (this.grade==""){
                    this.errors.grade = true;
                    has_error = true;    
                }

                if(has_error){
                    e.preventDefault();
                    e.stopPropagation();
                    return false;
                }
                return true;
            }
        },
        delimiters: ["[[", "]]"],
    }

    Vue.createApp(App).mount('#app')
    </script>
</body>
{% endblock content %}